# var1 := aaa
# var2 := $(var1)bbb
# var1 := ccc

# var1 = aaa
# var2 = $(var1)bbb
# var1 = ccc

# var1 = aaa
# var2 = $(var1)bbb
# var1 ?= ccc

var1 = aaa
var2 = $(var1)bbb
var1 += ccc

all:
	echo $(var2)